apiVersion: v1
kind: Service
metadata:
  name: devices-map-view-frontend
  labels:
    app: devices-map-view
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: devices-map-view
    tier: frontend